name: FEature dep
on:
  push:
    branches:
      - feature
  workflow_dispatch:
        
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: echo "This is fetaure branch"